### ISSUE TITLE
requireFile fails on Windows

### ISSUE THREAD

**Issue by tomconte** [ConsenSys/truffle-default-builder#4]
https://github.com/ConsenSys/truffle-default-builder/blob/master/processors/post/include_contracts.js#L15

This fails with the error below. Looks like some sort of file path escaping problem?

C:\Development\BlockChain\SolarChainHack>truffle.cmd build
Error: Cannot find module 'C:DevelopmentBlockChainSolarChainHacuildcontractsMigrations.sol.js' from 'C:\Users\tconte\AppData\Local\Temp'

**Comment by explosion78** [comment]
By inserting `file = file.replace(/[?*+^$[\]\\(){}|-]/g, "\\$&");` before line 18 solved this issue for me.

**Comment by tcoulter** [comment]
Great that you found the issue! The solution seems like overkill, however. Can you wrap `file` in `path.resolve()`? Node should take care of this for us...

**Comment by yubi00** [comment]
hi, i got a same problem on windows. i couldnt truffle build and truffle serve. so in which directory should i put this file? can anyone help me ?

**Comment by tcoulter** [comment]
@yubi00 This issue is old. If you having an issue, please open a new ticket so we can track it there. Thanks.
